project_id = "pitwxnerdhszuyiegyrt"

[functions.analyze-resume]
verify_jwt = false

[functions.extract-document-text]
verify_jwt = false

[functions.generate-interview-questions]
verify_jwt = false

[functions.send-candidate-notification]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false
